apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sftp-operator
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.operator.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: sftp-operator
    spec:
      containers:
      - name: {{ .Chart.Name }}-operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - operator
        resources:
{{ toYaml .Values.operator.resources | indent 12 }}

{{ if .Values.operator.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.operator.nodeSelector | indent 8 }}
{{ end }}

{{ if .Values.operator.tolerations }}
      tolerations:
{{ toYaml .Values.operator.tolerations | indent 8 }}
{{ end }}
