# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent

service:
  name: sftp
  type: ClusterIP
  externalPort: 22
  internalPort: 22

operator:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 50Mi
  nodeSelector:
    sftp-operator: 'true'

server:
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 50Mi
  nodeSelector:
    sftp-server: 'true'
  tolerations:
    - key: node-role.kubernetes.io/node
      operator: Exists
      effect: NoSchedule
